#pragma once

#define PRTN_PROJECT_NAME      "PRTN"
#define PRTN_PROJECT_FULL_NAME "PRTS Node"
#define PRTN_BOARD_NAME        "AirM2M CORE ESP32-C3"
#define PRTN_VERSION_STRING    "0.1.0"
#define PRTN_NODE_NAME         "PRTN-NODE"
#define PRTN_NODE_ID           "PRTN-NODE-001"

#ifndef PRTN_SERIAL_BAUD
#define PRTN_SERIAL_BAUD 115200
#endif

#ifndef PRTN_LED_PIN
#define PRTN_LED_PIN 12
#endif

#ifndef PRTN_LED_PIN_AUX
#define PRTN_LED_PIN_AUX 13
#endif

#ifndef PRTN_LED_ACTIVE_HIGH
#define PRTN_LED_ACTIVE_HIGH 1
#endif

#ifndef PRTN_IIC_SCL_PIN
#define PRTN_IIC_SCL_PIN 5
#endif

#ifndef PRTN_IIC_SDA_PIN
#define PRTN_IIC_SDA_PIN 4
#endif

#ifndef PRTN_IIC_FREQUENCY
#define PRTN_IIC_FREQUENCY 400000
#endif

#ifndef PRTN_IIC_TIMEOUT_MS
#define PRTN_IIC_TIMEOUT_MS 50
#endif

#ifndef PRTN_WIFI_MODE
#define PRTN_WIFI_MODE Wifi::Mode::AP
#endif

#ifndef PRTN_WIFI_AP_SSID
#define PRTN_WIFI_AP_SSID "PRTN-AP-MQTT"
#endif

#ifndef PRTN_WIFI_AP_PASSWORD
#define PRTN_WIFI_AP_PASSWORD "12345678"
#endif

#ifndef PRTN_WIFI_AP_CHANNEL
#define PRTN_WIFI_AP_CHANNEL 1
#endif

#ifndef PRTN_WIFI_AP_MAX_CLIENTS_NUM
#define PRTN_WIFI_AP_MAX_CLIENTS_NUM 4
#endif

#ifndef PRTN_MQTT_SERVER_MAX_CLIENTS_NUM
#define PRTN_MQTT_SERVER_MAX_CLIENTS_NUM 4
#endif

#ifndef PRTN_MQTT_SERVER_PORT
#define PRTN_MQTT_SERVER_PORT 1883
#endif

#ifndef PRTN_MQTT_SERVER_MAX_SUBSCRIPTIONS_NUM
#define PRTN_MQTT_SERVER_MAX_SUBSCRIPTIONS_NUM 16
#endif

#ifndef PRTN_MQTT_PACKET_BUFFER_SIZE
#define PRTN_MQTT_PACKET_BUFFER_SIZE 256
#endif

#ifndef PRTN_MQTT_SERVER_VERBOSE_LOG
#define PRTN_MQTT_SERVER_VERBOSE_LOG 1
#endif
