#pragma once

#define PRTN_NODE_PROFILE_AMA10 1
#define PRTN_NODE_PROFILE_M3    2

#ifndef PRTN_NODE_PROFILE
#define PRTN_NODE_PROFILE PRTN_NODE_PROFILE_AMA10
#endif

#if defined(PRTN_ESPNOW_TEST_ENABLE_SENDER) && !defined(PRTN_ESPNOW_ECHO_ENABLE_SENDER)
#define PRTN_ESPNOW_ECHO_ENABLE_SENDER PRTN_ESPNOW_TEST_ENABLE_SENDER
#endif

#if defined(PRTN_ESPNOW_TEST_ENABLE_RECEIVER) && !defined(PRTN_ESPNOW_ECHO_ENABLE_RECEIVER)
#define PRTN_ESPNOW_ECHO_ENABLE_RECEIVER PRTN_ESPNOW_TEST_ENABLE_RECEIVER
#endif

#if PRTN_NODE_PROFILE == PRTN_NODE_PROFILE_M3

#ifndef PRTN_NODE_ID
#define PRTN_NODE_ID "M3"
#endif

#ifndef PRTN_NODE_NAME
#define PRTN_NODE_NAME "M3"
#endif

#ifndef PRTN_ESPNOW_ECHO_ENABLE_SENDER
#define PRTN_ESPNOW_ECHO_ENABLE_SENDER 0
#endif

#ifndef PRTN_ESPNOW_ECHO_ENABLE_RECEIVER
#define PRTN_ESPNOW_ECHO_ENABLE_RECEIVER 1
#endif

#elif PRTN_NODE_PROFILE == PRTN_NODE_PROFILE_AMA10

#ifndef PRTN_NODE_ID
#define PRTN_NODE_ID "AMA-10"
#endif

#ifndef PRTN_NODE_NAME
#define PRTN_NODE_NAME "AMA-10"
#endif

#ifndef PRTN_ESPNOW_ECHO_ENABLE_SENDER
#define PRTN_ESPNOW_ECHO_ENABLE_SENDER 1
#endif

#ifndef PRTN_ESPNOW_ECHO_ENABLE_RECEIVER
#define PRTN_ESPNOW_ECHO_ENABLE_RECEIVER 1
#endif

#else
#error "Unsupported PRTN_NODE_PROFILE"
#endif

// Backward-compatible names for older local.mk files.
#ifndef PRTN_ESPNOW_TEST_ENABLE_SENDER
#define PRTN_ESPNOW_TEST_ENABLE_SENDER PRTN_ESPNOW_ECHO_ENABLE_SENDER
#endif

#ifndef PRTN_ESPNOW_TEST_ENABLE_RECEIVER
#define PRTN_ESPNOW_TEST_ENABLE_RECEIVER PRTN_ESPNOW_ECHO_ENABLE_RECEIVER
#endif
