#pragma once

#include "src/cfg/ProfileConfig.h"

// WiFi -----------------------------------------------------------------------
#ifndef PRTN_WIFI_MODE
#define PRTN_WIFI_MODE Wifi::Mode::STA
#endif

#ifndef PRTN_WIFI_AP_SSID
#define PRTN_WIFI_AP_SSID "PRTN-AP-MQTT"
#endif

#ifndef PRTN_WIFI_AP_PASSWORD
#define PRTN_WIFI_AP_PASSWORD "12345678"
#endif

#ifndef PRTN_WIFI_AP_CHANNEL
#define PRTN_WIFI_AP_CHANNEL 1
#endif

#ifndef PRTN_WIFI_AP_MAX_CLIENTS_NUM
#define PRTN_WIFI_AP_MAX_CLIENTS_NUM 4
#endif

#ifndef PRTN_WIFI_STA_SSID
#define PRTN_WIFI_STA_SSID PRTN_WIFI_AP_SSID
#endif

#ifndef PRTN_WIFI_STA_PASSWORD
#define PRTN_WIFI_STA_PASSWORD PRTN_WIFI_AP_PASSWORD
#endif

#ifndef PRTN_WIFI_STA_HOSTNAME
#define PRTN_WIFI_STA_HOSTNAME PRTN_NODE_ID
#endif

#ifndef PRTN_WIFI_STA_RECONNECT_MS
#define PRTN_WIFI_STA_RECONNECT_MS 5000
#endif

#ifndef PRTN_WIFI_STA_CONNECT
#define PRTN_WIFI_STA_CONNECT 0
#endif

#ifndef PRTN_WIFI_STA_CHANNEL
#define PRTN_WIFI_STA_CHANNEL 1
#endif

// ESP-NOW service ------------------------------------------------------------
#ifndef PRTN_ESPNOW_DISCOVERY_INTERVAL_MS
#define PRTN_ESPNOW_DISCOVERY_INTERVAL_MS 1000
#endif

#ifndef PRTN_ESPNOW_HEARTBEAT_INTERVAL_MS
#define PRTN_ESPNOW_HEARTBEAT_INTERVAL_MS 2000
#endif

// ESP-NOW echo test application ---------------------------------------------
#if defined(PRTN_ESPNOW_TEST_PAYLOAD_LEN) && !defined(PRTN_ESPNOW_ECHO_PAYLOAD_LEN)
#define PRTN_ESPNOW_ECHO_PAYLOAD_LEN PRTN_ESPNOW_TEST_PAYLOAD_LEN
#endif

#if defined(PRTN_ESPNOW_TEST_SEND_INTERVAL_MS) && !defined(PRTN_ESPNOW_ECHO_SEND_INTERVAL_MS)
#define PRTN_ESPNOW_ECHO_SEND_INTERVAL_MS PRTN_ESPNOW_TEST_SEND_INTERVAL_MS
#endif

#if defined(PRTN_ESPNOW_TEST_USE_ACK) && !defined(PRTN_ESPNOW_ECHO_USE_ACK)
#define PRTN_ESPNOW_ECHO_USE_ACK PRTN_ESPNOW_TEST_USE_ACK
#endif

#if defined(PRTN_ESPNOW_TEST_VERBOSE_LOG) && !defined(PRTN_ESPNOW_ECHO_VERBOSE_LOG)
#define PRTN_ESPNOW_ECHO_VERBOSE_LOG PRTN_ESPNOW_TEST_VERBOSE_LOG
#endif

#if defined(PRTN_ESPNOW_TEST_STATS_LOG) && !defined(PRTN_ESPNOW_ECHO_STATS_LOG)
#define PRTN_ESPNOW_ECHO_STATS_LOG PRTN_ESPNOW_TEST_STATS_LOG
#endif

#if defined(PRTN_ESPNOW_TEST_STATS_LOG_INTERVAL_MS) && !defined(PRTN_ESPNOW_ECHO_STATS_LOG_INTERVAL_MS)
#define PRTN_ESPNOW_ECHO_STATS_LOG_INTERVAL_MS PRTN_ESPNOW_TEST_STATS_LOG_INTERVAL_MS
#endif

#if defined(PRTN_ESPNOW_ACTIVITY_LED_WINDOW_MS) && !defined(PRTN_ESPNOW_ECHO_ACTIVITY_LED_WINDOW_MS)
#define PRTN_ESPNOW_ECHO_ACTIVITY_LED_WINDOW_MS PRTN_ESPNOW_ACTIVITY_LED_WINDOW_MS
#endif

#if defined(PRTN_ESPNOW_ACTIVITY_LED_INTERVAL_MS) && !defined(PRTN_ESPNOW_ECHO_ACTIVITY_LED_INTERVAL_MS)
#define PRTN_ESPNOW_ECHO_ACTIVITY_LED_INTERVAL_MS PRTN_ESPNOW_ACTIVITY_LED_INTERVAL_MS
#endif

#if defined(PRTN_ESPNOW_TEST_UPDATE_WIFI) && !defined(PRTN_NODE_CONTROLLER_UPDATE_WIFI)
#define PRTN_NODE_CONTROLLER_UPDATE_WIFI PRTN_ESPNOW_TEST_UPDATE_WIFI
#endif

#if defined(PRTN_ESPNOW_TEST_WIFI_STATUS_LOG) && !defined(PRTN_NODE_CONTROLLER_WIFI_STATUS_LOG)
#define PRTN_NODE_CONTROLLER_WIFI_STATUS_LOG PRTN_ESPNOW_TEST_WIFI_STATUS_LOG
#endif

#ifndef PRTN_ESPNOW_ECHO_PAYLOAD_LEN
#define PRTN_ESPNOW_ECHO_PAYLOAD_LEN 30
#endif

#ifndef PRTN_ESPNOW_ECHO_SEND_INTERVAL_MS
#define PRTN_ESPNOW_ECHO_SEND_INTERVAL_MS 20
#endif

#ifndef PRTN_ESPNOW_ECHO_USE_ACK
#define PRTN_ESPNOW_ECHO_USE_ACK 0
#endif

#ifndef PRTN_ESPNOW_ECHO_VERBOSE_LOG
#define PRTN_ESPNOW_ECHO_VERBOSE_LOG 0
#endif

#ifndef PRTN_ESPNOW_ECHO_STATS_LOG
#define PRTN_ESPNOW_ECHO_STATS_LOG 1
#endif

#ifndef PRTN_ESPNOW_ECHO_STATS_LOG_INTERVAL_MS
#define PRTN_ESPNOW_ECHO_STATS_LOG_INTERVAL_MS 1000
#endif

#ifndef PRTN_ESPNOW_ECHO_ACTIVITY_LED_WINDOW_MS
#define PRTN_ESPNOW_ECHO_ACTIVITY_LED_WINDOW_MS 1200
#endif

#ifndef PRTN_ESPNOW_ECHO_ACTIVITY_LED_INTERVAL_MS
#define PRTN_ESPNOW_ECHO_ACTIVITY_LED_INTERVAL_MS 60
#endif

#ifndef PRTN_NODE_CONTROLLER_UPDATE_WIFI
#define PRTN_NODE_CONTROLLER_UPDATE_WIFI 0
#endif

#ifndef PRTN_NODE_CONTROLLER_WIFI_STATUS_LOG
#define PRTN_NODE_CONTROLLER_WIFI_STATUS_LOG 0
#endif

// Backward-compatible names for older local.mk files.
#ifndef PRTN_ESPNOW_TEST_PAYLOAD_LEN
#define PRTN_ESPNOW_TEST_PAYLOAD_LEN PRTN_ESPNOW_ECHO_PAYLOAD_LEN
#endif

#ifndef PRTN_ESPNOW_TEST_SEND_INTERVAL_MS
#define PRTN_ESPNOW_TEST_SEND_INTERVAL_MS PRTN_ESPNOW_ECHO_SEND_INTERVAL_MS
#endif

#ifndef PRTN_ESPNOW_TEST_USE_ACK
#define PRTN_ESPNOW_TEST_USE_ACK PRTN_ESPNOW_ECHO_USE_ACK
#endif

#ifndef PRTN_ESPNOW_TEST_VERBOSE_LOG
#define PRTN_ESPNOW_TEST_VERBOSE_LOG PRTN_ESPNOW_ECHO_VERBOSE_LOG
#endif

#ifndef PRTN_ESPNOW_TEST_STATS_LOG
#define PRTN_ESPNOW_TEST_STATS_LOG PRTN_ESPNOW_ECHO_STATS_LOG
#endif

#ifndef PRTN_ESPNOW_TEST_STATS_LOG_INTERVAL_MS
#define PRTN_ESPNOW_TEST_STATS_LOG_INTERVAL_MS PRTN_ESPNOW_ECHO_STATS_LOG_INTERVAL_MS
#endif

#ifndef PRTN_ESPNOW_ACTIVITY_LED_WINDOW_MS
#define PRTN_ESPNOW_ACTIVITY_LED_WINDOW_MS PRTN_ESPNOW_ECHO_ACTIVITY_LED_WINDOW_MS
#endif

#ifndef PRTN_ESPNOW_ACTIVITY_LED_INTERVAL_MS
#define PRTN_ESPNOW_ACTIVITY_LED_INTERVAL_MS PRTN_ESPNOW_ECHO_ACTIVITY_LED_INTERVAL_MS
#endif

#ifndef PRTN_ESPNOW_TEST_UPDATE_WIFI
#define PRTN_ESPNOW_TEST_UPDATE_WIFI PRTN_NODE_CONTROLLER_UPDATE_WIFI
#endif

#ifndef PRTN_ESPNOW_TEST_WIFI_STATUS_LOG
#define PRTN_ESPNOW_TEST_WIFI_STATUS_LOG PRTN_NODE_CONTROLLER_WIFI_STATUS_LOG
#endif

// MQTT -----------------------------------------------------------------------
#ifndef PRTN_MQTT_SERVER_MAX_CLIENTS_NUM
#define PRTN_MQTT_SERVER_MAX_CLIENTS_NUM 4
#endif

#ifndef PRTN_MQTT_SERVER_PORT
#define PRTN_MQTT_SERVER_PORT 1883
#endif

#ifndef PRTN_MQTT_SERVER_MAX_SUBSCRIPTIONS_NUM
#define PRTN_MQTT_SERVER_MAX_SUBSCRIPTIONS_NUM 16
#endif

#ifndef PRTN_MQTT_PACKET_BUFFER_SIZE
#define PRTN_MQTT_PACKET_BUFFER_SIZE 256
#endif

#ifndef PRTN_MQTT_SERVER_VERBOSE_LOG
#define PRTN_MQTT_SERVER_VERBOSE_LOG 1
#endif

#ifndef PRTN_MQTT_CLIENT_HOST
#define PRTN_MQTT_CLIENT_HOST "192.168.4.1"
#endif

#ifndef PRTN_MQTT_CLIENT_PORT
#define PRTN_MQTT_CLIENT_PORT 1883
#endif

#ifndef PRTN_MQTT_CLIENT_ID
#define PRTN_MQTT_CLIENT_ID PRTN_NODE_ID "-CLIENT"
#endif

#ifndef PRTN_MQTT_CLIENT_USERNAME
#define PRTN_MQTT_CLIENT_USERNAME nullptr
#endif

#ifndef PRTN_MQTT_CLIENT_PASSWORD
#define PRTN_MQTT_CLIENT_PASSWORD nullptr
#endif

#ifndef PRTN_MQTT_CLIENT_KEEP_ALIVE_SEC
#define PRTN_MQTT_CLIENT_KEEP_ALIVE_SEC 30
#endif

#ifndef PRTN_MQTT_CLIENT_MAX_PACKET_SIZE
#define PRTN_MQTT_CLIENT_MAX_PACKET_SIZE PRTN_MQTT_PACKET_BUFFER_SIZE
#endif

#ifndef PRTN_MQTT_CLIENT_RECONNECT_MS
#define PRTN_MQTT_CLIENT_RECONNECT_MS 5000
#endif

#ifndef PRTN_MQTT_CLIENT_TEST_TOPIC
#define PRTN_MQTT_CLIENT_TEST_TOPIC "prtn/test/client"
#endif

#ifndef PRTN_MQTT_CLIENT_TEST_PAYLOAD
#define PRTN_MQTT_CLIENT_TEST_PAYLOAD "{\"source\":\"" PRTN_NODE_ID "\",\"kind\":\"client-test\"}"
#endif

#ifndef PRTN_MQTT_CLIENT_TEST_PUBLISH_MS
#define PRTN_MQTT_CLIENT_TEST_PUBLISH_MS 5000
#endif

#ifndef PRTN_MQTT_CLIENT_VERBOSE_LOG
#define PRTN_MQTT_CLIENT_VERBOSE_LOG 1
#endif
